version: '3.3'
services:
  php:
    volumes:
      - ./smf:/var/html/www/
      - ./log.conf:/usr/local/etc/php-fpm.d/zz-log.conf
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: ${CONTAINER_PREFIX}php

  nginx:
    ports:
      - "${EXTERNAL_PORT}:${NGINX_PORT}"
    volumes:
      - ./smf:/var/html/www/
      - ./site.conf:/etc/nginx/conf.d/default.conf
    environment:
      - NGINX_HOST=${NGINX_HOST}
      - NGINX_PORT=${NGINX_PORT}
    image: nginx:1.17.4
    depends_on:
      - php
    container_name: ${CONTAINER_PREFIX}nginx

  mysql:
    image: mysql:${MYSQL_VERSION}
    ports:
      - "${EXTERNAL_MYSQL_PORT}:${DB_PORT}"
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./smf:/var/html/www/
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    container_name: ${CONTAINER_PREFIX}mysql
