version: '3.3'
services:
  php:
    volumes:
      - ./smf:/smf
      - ./log.conf:/usr/local/etc/php-fpm.d/zz-log.conf
    build:
      context: .
      dockerfile: /docker/php/Dockerfile
    container_name: php

  nginx:
    ports:
      - "80:80"
    volumes:
      - ./smf:/smf
      - ./site.conf:/etc/nginx/conf.d/default.conf
    environment:
      - NGINX_HOST=smf.local
      - NGINX_PORT=80
    image: nginx:1.17.4
    depends_on:
      - php
    container_name: nginx

  mysql:
    image: mysql:5.7
    ports:
      - "33086:3306"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_DATABASE= smf
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    container_name: mysql
