version: '3.3'
services:
  php:
    volumes:
      - ./smf:/var/html/www/
      - ./log.conf:/usr/local/etc/php-fpm.d/zz-log.conf
    build:
      context: .
      dockerfile: /docker/php/Dockerfile
      args:
        - GITHUB_USERNAME=${GITHUB_USERNAME}
        - GITHUB_TOKEN=${GITHUB_TOKEN}
        - PHP_VERSION=${PHP_VERSION}
    container_name: php

  nginx:
    ports:
      - "80:80"
    volumes:
      - ./smf:/var/html/www/
      - ./site.conf:/etc/nginx/conf.d/default.conf
    environment:
      - NGINX_HOST=${NGINX_HOST}
      - NGINX_PORT=${NGINX_PORT}
    image: nginx:1.17.4
    depends_on:
      - php
    container_name: nginx

  mysql:
    image: mysql:5.7
    ports:
      - "33086:${DB_PORT}"
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./smf:/var/html/www/
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    container_name: mysql
